// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8xVvjTH5mBIw6VS6B8tbxI81FyD2Mfw',
    appId: '1:617100248967:android:1b075636f3e9f52eacb522',
    messagingSenderId: '617100248967',
    projectId: 'flutterfirebase-9aae9',
    databaseURL: 'https://flutterfirebase-9aae9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-9aae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd3_YFyhxH0qfsU1Zs9NFf09bCvQT6gZA',
    appId: '1:617100248967:ios:abe293a6a123f2d9acb522',
    messagingSenderId: '617100248967',
    projectId: 'flutterfirebase-9aae9',
    databaseURL: 'https://flutterfirebase-9aae9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfirebase-9aae9.appspot.com',
    iosBundleId: 'com.note.note',
  );
}
